import {
  FaPenRuler,
  FaCode,
  FaBrain,
  FaChartLine,
  FaLandmark,
  FaHeartPulse,
  FaLayerGroup,
  FaArrowTrendUp,
  FaStar,
  FaGlobe,
  FaGem,
  FaBan,
  FaMicrochip,
  FaUserTie,
  FaMagnifyingGlass,
  FaRocket,
  FaDatabase,
  FaBolt,
  FaShieldHalved,
  FaLock,
  FaUniversalAccess,
  FaAward,
  FaArrowRight,
  FaChevronDown,
  FaPhone,
  FaBars,
  FaXmark,
  FaCheck,
  FaCircleDot,
  FaCircleNodes,
  FaCodeBranch,
  FaFolderOpen,
  FaEnvelope,
  FaLocationDot,
  FaClock,
  FaMedal,
  FaSun,
  FaMoon,
  FaReact,
  FaNodeJs,
  FaPython,
  FaAws,
  FaDocker,
  FaGithub,
  FaFigma,
  FaStripe,
  FaLinkedin,
  FaXTwitter,
  FaDribbble,
  FaQuoteRight,
  FaEye,
  FaBullseye,
  FaHandshake,
  FaPlay,
  FaMobileScreen,
  FaStore,
  FaGraduationCap,
  FaBuilding,
  FaClipboardCheck,
  FaPalette,
  FaComments,
  FaLightbulb,
  FaMinus,
  FaTriangleExclamation,
  FaPaperPlane,
  FaCalendar,
  FaHeadset,
} from "react-icons/fa6";

const registry = {
  design: FaPenRuler,
  code: FaCode,
  ai: FaBrain,
  brain: FaBrain,
  growth: FaChartLine,
  bank: FaLandmark,
  health: FaHeartPulse,
  saas: FaLayerGroup,
  trend: FaArrowTrendUp,
  star: FaStar,
  globe: FaGlobe,
  gem: FaGem,
  ban: FaBan,
  chip: FaMicrochip,
  team: FaUserTie,
  search: FaMagnifyingGlass,
  rocket: FaRocket,
  database: FaDatabase,
  next: FaBolt,
  bolt: FaBolt,
  shield: FaShieldHalved,
  lock: FaLock,
  access: FaUniversalAccess,
  award: FaAward,
  "arrow-right": FaArrowRight,
  "chevron-down": FaChevronDown,
  phone: FaPhone,
  bars: FaBars,
  close: FaXmark,
  check: FaCheck,
  "circle-dot": FaCircleDot,
  "circle-nodes": FaCircleNodes,
  "code-branch": FaCodeBranch,
  "folder-open": FaFolderOpen,
  envelope: FaEnvelope,
  location: FaLocationDot,
  clock: FaClock,
  medal: FaMedal,
  sun: FaSun,
  moon: FaMoon,
  react: FaReact,
  node: FaNodeJs,
  python: FaPython,
  aws: FaAws,
  docker: FaDocker,
  github: FaGithub,
  figma: FaFigma,
  stripe: FaStripe,
  linkedin: FaLinkedin,
  "x-twitter": FaXTwitter,
  dribbble: FaDribbble,
  quote: FaQuoteRight,
  eye: FaEye,
  target: FaBullseye,
  handshake: FaHandshake,
  play: FaPlay,
  mobile: FaMobileScreen,
  store: FaStore,
  education: FaGraduationCap,
  building: FaBuilding,
  clipboard: FaClipboardCheck,
  palette: FaPalette,
  comments: FaComments,
  lightbulb: FaLightbulb,
  minus: FaMinus,
  warning: FaTriangleExclamation,
  x: FaXmark,
  "paper-plane": FaPaperPlane,
  calendar: FaCalendar,
  headset: FaHeadset,
};

export function Icon({ name, className, ...props }) {
  const Glyph = registry[name];
  if (!Glyph) return null;
  return <Glyph className={className} aria-hidden="true" {...props} />;
}

export default Icon;
